Feat/adding argocd repository project scoped
oboukili/terraform-provider-argocd pull request #189
Opened 2022-06-03 12:54 UTC by felipem1210

2022-06-13 13:36 UTC, oboukili requested changes
Thanks! This PR is missing acceptance tests, could you add them?

2022-06-13 13:36 UTC, oboukili commented on scripts/testacc_prepare_env.sh
> +echo "\n--- Install ArgoCD ${ARGOCD_VERSION:-v2.4.0-rc3}\n"
Let's not use release candidate by default for testing please

2022-06-14 17:57 UTC, felipem1210 commented
Hi @oboukili , I checked the test code for projects and repositories and I am not sure how can I create the project token and after that use that token to test the creation of a project scoped repo using that token. Honestly, I'm really really noob in Go programming so I will take my time trying to create that test :D (unless somebody want to give a hand)

2022-06-29 21:34 UTC, felipem1210 commented
Will try to do it next week

2022-08-08 13:08 UTC, closed without merging